language: csharp

sudo: false

mono: 5.12.0

dotnet: 2.1.300

before_install:
  - chmod +x build.sh

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet : 2.1.300
    - os: osx
      osx_image: xcode9.1
      dotnet : 2.1.300
      dist: trusty
      sudo: required
      
script: 
  - ./build.sh
