version: 1.0.0.{build}

image: Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off

artifacts:
  - path: 'dist\FsPublicSuffix.*.nupkg'
    name: nupkg

deploy:
  - provider: NuGet
    artifact: nupkg
    api_key:
      secure: taw4vkPRI4Zxhu7wxTayZGlKUv54FOb81TJ+nBAGs64ld1pzcP+94F5ZHn4XAfKj
    on:
      APPVEYOR_REPO_TAG: true
